//
//  DFLocalizable.swift
//  FpcDF
//
//  Created by 陳仲堯 on 2020/1/31.
//  Copyright © 2020 陳仲堯. All rights reserved.
//

import Foundation
import UIKit

// Important!! LocalizableKey.swift must sync with Localizable.strins

enum DFLocalizable: String {
    case APP_NAME = "APP_NAME"
    case APP_VERSION = "APP_VERSION"
    
    case NAME = "NAME"
    case ACCOUNT = "ACCOUNT"
    
    case LOGIN_ENTER_ACCOUNT = "LOGIN_ENTER_ACCOUNT"
    case LOGIN_ENTER_PASSWORD = "LOGIN_ENTER_PASSWORD"
    
    case LOGIN_FAILED = "LOGIN_FAILED"
    case LOGIN_ACCOUNT_PASSWORD_ERROR = "LOGIN_ACCOUNT_PASSWORD_ERROR"
    case LOGIN_ACCOUNT_IS_NOT_EXIST = "LOGIN_ACCOUNT_IS_NOT_EXIST"
    case LOGIN_ACCOUNT_NO_PERMISSION = "LOGIN_ACCOUNT_NO_PERMISSION"
    case LOGIN_ACCOUNT_DISABLED = "LOGIN_ACCOUNT_DISABLED"
    
    case LOGOUT = "LOGOUT"
    
    case APP_FORCE_UPDATE = "APP_FORCE_UPDATE"
    case APP_UPDATE_TIP = "APP_UPDATE_TIP"
    case APP_FORCE_LOGOUT = "APP_FORCE_LOGOUT"
    
    case PROMPT_DELETE_NOTIFICATION = "PROMPT_DELETE_NOTIFICATION"
    
    case COMMAND_CONFIRM = "COMMAND_CONFIRM"
    case COMMAND_CANCEL = "COMMAND_CANCEL"
    case COMMAND_UPDATE_APP = "COMMAND_UPDATE_APP"
    case COMMAND_SKIP = "COMMAND_SKIP"
    
    case MESSAGE_TIP = "MESSAGE_TIP"
    
    case BACK = "BACK"
    case SETTING = "SETTING"
    case NOTIFICATION = "NOTIFICATION"
    
    case NO_CONTENT = "NO_CONTENT"
    case NO_SETTING_ITEM = "NO_SETTING_ITEM"
    
    case ENTRUST = "ENTRUST"
    case ROUTINE = "ROUTINE"
    case STATUS_A = "STATUS_A"
    case STATUS_C = "STATUS_C"
    case STATUS_V = "STATUS_V"
    
    case LIMS_SAMPLE_NOTIFICATIONS_TO_FPCIM = "LIMS_SAMPLE_NOTIFICATIONS_TO_FPCIM"
    case LIMS_SAMPLE_COMPLETED_NOTIFICATION = "LIMS_SAMPLE_COMPLETED_NOTIFICATION"
    
    
    case SAMPLE_TEST_OUT_OF_RANGE = "SAMPLE_TEST_OUT_OF_RANGE"
    case SAMPLE_INSPECTION_COMPLETED = "SAMPLE_INSPECTION_COMPLETED"
    case LIMS_INSTRUMENT_VALUE_OUT_OF_RANGE = "LIMS_INSTRUMENT_VALUE_OUT_OF_RANGE"
    case LIMS_SQC_ALARM = "LIMS_SQC_ALARM"
    
    case JW_LIMS_SAMPLE_TEST_OUT_OF_RANGE = "JW_LIMS_SAMPLE_TEST_OUT_OF_RANGE"
    case JW_LIMS_SAMPLE_INSPECTION_COMPLETED = "JW_LIMS_SAMPLE_INSPECTION_COMPLETED"
    case JW_LIMS_INSTRUMENT_VALUE_OUT_OF_RANGE = "JW_LIMS_INSTRUMENT_VALUE_OUT_OF_RANGE"
    case JW_LIMS_SQC_ALARM = "JW_LIMS_SQC_ALARM"
    
    case HYDUTY_OFF_DUTY_EMPLOYEE = "HYDUTY_OFF_DUTY_EMPLOYEE"
    
    case WEB_LINK = "WEB_LINK"
    
    case CFP_EQUIPMENT_ACTION = "CFP_EQUIPMENT_ACTION"
    case CFP_POST_COMMENT = "CFP_POST_COMMENT"
    
    case SELECT_END_DATE = "SELECT_END_DATE"
    
    case NO_SHIP_LOCATION = "NO_SHIP_LOCATION"
    
    case AVERAGE_CALCULATION = "AVERAGE_CALCULATION"
    case CALCULATE = "CALCULATE"
    
    case SUPPLIER = "SUPPLIER"
    case BEGIN_DATE = "BEGIN_DATE"
    case END_DATE = "END_DATE"
    
    case CFP_CREATE = "CFP_CREATE"
    case CFP_WAITING = "CFP_WAITING"
    case CFP_PROCESSING = "CFP_PROCESSING"
    case CFP_COMPLETED = "CFP_COMPLETED"
    
    case END
    
    static func valueOf(_ key: DFLocalizable) -> String {
        return NSLocalizedString(key.rawValue, comment: key.rawValue)
    }
}

